# Default values for .helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: asvioapi-dev
appLabel: asvioapi-dev
containerName: asvioapi-container-dev
appHost: asvioapidev.inikon.com.ua

# Type issuer ["letsencrypt-prod", "letsencrypt-staging"]
issuerType: "letsencrypt-prod"

replications:
  replicaCount: 3
  minReplicasHPA: 3
  maxReplicasHPA: 10

#data base credintial ["prod", "dev"]
database: dev

containerBackPort: 8000
exposePort: 8080

image:
  repository: ghcr.io/dinikon/asvio-crm-api-dev
  tag: latest

resources:
  presetOne:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1024Mi"
      cpu: "500m"
  presetTwo:
    requests:
      memory: "256Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "200m"

config:
  # Bool значения указывать "True"
  debug: "True"
  allowedHost: "asvioapidev.inikon.com.ua"
  corsAllowedOrigins: "https://asvioapidev.inikon.com.ua, https://asviodev.inikon.com.ua, http://localhost:8080, http://127.0.0.1:9000, 
    http://127.0.0.1:5173, http://localhost:5173"
  corsAllowHeaders: "accept, authorization, content-type, user-agent, x-csrftoken, x-requested-with, x-project-guid"
  corsTrustedOrigins: "https://asvioapidev.inikon.com.ua, https://asviodev.inikon.com.ua"
  accessTokenLifetime: 512
  refreshTokenLifetime: 1024