"""create telegram client table

Revision ID: c567773a8d5e
Revises: 
Create Date: 2024-09-21 14:37:54.202500

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c567773a8d5e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "b_crm_t_telegram_clients",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.Integer(), nullable=False),
        sa.Column("data_hash", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint(
            "id",
            "customer_id",
            "telegram_id",
            name=op.f("pk_b_crm_t_telegram_clients"),
        ),
        sa.UniqueConstraint(
            "customer_id", name=op.f("uq_b_crm_t_telegram_clients_customer_id")
        ),
        sa.UniqueConstraint("id", name=op.f("uq_b_crm_t_telegram_clients_id")),
        sa.UniqueConstraint(
            "telegram_id", name=op.f("uq_b_crm_t_telegram_clients_telegram_id")
        ),
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("b_crm_t_telegram_clients", schema="public")
    # ### end Alembic commands ###
