apiVersion: apps/v1
kind: Deployment
metadata:
  name: finrock-auth-api-deployment
  namespace: finrock-backend
  labels:
    app: finrock-auth-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finrock-auth-api-app
  template:
    metadata:
      labels:
        app: finrock-auth-api-app
    spec:
      containers:
      - name: finrock-auth-api-container
        image: ghcr.io/dinikon/finrock-auth-api-dev:v0.0.10
        ports:
        - containerPort: 8000
        env:
          - name: BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: finrock-auth-api-secret
                key: bot-token
          - name: AUTH-APP__DB__URL
            valueFrom:
              secretKeyRef:
                name: finrock-auth-api-secret
                key: db-url
        volumeMounts:
        - name: fastapi-storage
          mountPath: /fastapi
      volumes:
      - name: fastapi-storage
        emptyDir: {}
