apiVersion: v1
kind: Service
metadata:
  name: finrock-auth-api-service
  namespace: finrock-backend
  labels:
    app: finrock-auth-api-app
spec:
  selector:
    app: finrock-auth-api-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
